### PR TITLE
Remove unused `FormatUnit` newtype.

### PR DESCRIPTION
**Pull request by tomprince**

### CODE REVIEW

**Comment by untitaker** [comment]
I guess the intention was to add actual styling information later, but yeah. Thanks!

**Comment by tomprince** [comment]
It's actually the other way around, it used to support styling information, but the wrapper wasn't dropped when the other fields were removed.

**Comment by untitaker** [comment]
I see.

**Comment by tomprince** [comment]
See #91 (in particular fe6dab0f81e77224e553fbcb1179f3003f86f007).

**Pull request merged**
