### PR TITLE
Add IP Address

### PR DESCRIPTION
**Pull request by gsquire**
A simple change to add the remote address to the logging formatter. Solves #66

### CODE REVIEW

**Comment by gsquire** [comment]
@reem any thoughts on this?

**Comment by gsquire** [comment]
Rebased my commit.

**Comment by wdv4758h** [comment]
I just thinking about the same thing, then I find this PR. 😄 
I hope this feature can be added soon. 🙏

**Comment by reem** [comment]
Looks great, thanks! Sorry for sitting on this.

**Pull request merged**
