### PR TITLE
(feat) Log errors

### PR DESCRIPTION
**Pull request by adamreeve**
This addresses #58

I've made this change on top of zmbush's fixes in #57 which get logger working with the latest iron. I can tidy this PR up once that PR is merged.

### CODE REVIEW

**Comment by zmbush** [comment]
Hey @adamreeve, my changes have landed, so you should be able to update your PR now!

**Comment by adamreeve** [comment]
Cool, thanks @zmbush, I've rebased this on top of the latest master. cc @reem

**Comment by reem** [comment]
Sorry for sitting on this, this looks great. Thank you very much!

**Comment by Stebalien** [comment]
This doesn't completely address #58 as it *still* doesn't actually log the actual error, just the response.

**Pull request merged**
